# Generated by Django 6.0.2 on 2026-03-06 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationapp', '0002_company_product_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='adr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relationapp.address'),
        ),
    ]
