# Generated by Django 4.2.7 on 2026-01-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('fees', models.FloatField()),
                ('info', models.TextField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
